stages:
  - test
  - linter
  - sonar


default:
  image: python:3.8
  timeout: 10m


workflow:
  rules:
    # TODO Should replaced to CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED if GitCI_RUNNER_VERSION will upper then 15.2
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" &&
        ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^release\/.*$/ ||
        $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" ||
        $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" ||
        $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main")
    - if: $CI_PIPELINE_SOURCE == "schedule"


variables: &global-variables
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  SONAR_HOST_URL: ${SONAR_URL}
  SONAR_PROJECT: "m3-modular-cli"
  GIT_DEPTH: 10
  CE_TASK_URL: ""
  SONAR_FILE_PATH: 'target/sonar/report-task.txt'


include:
  - local: .gitlab/ci/dev.gitlab-ci.yml
  - local: .gitlab/ci/sonar.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

.secret-analyzer:
  artifacts:
    expire_in: 1 day
    when: always

secret_detection:
  rules:
    - !reference [.only-default, rules]
  variables:
    GIT_DEPTH: 100

code_quality:
  stage: linter
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      changes:
        - ./**
  artifacts:
    expire_in: 2 day
    when: always
    paths: [ gl-code-quality-report.json ]
